NAME := controls-engineering-in-frc

# Make does not offer a recursive wildcard function, so here's one:
rwildcard=$(wildcard $1$2) $(foreach dir,$(wildcard $1*),$(call rwildcard,$(dir)/,$2))

# Python files that generate SVG files
PY := $(filter-out ./bookutil/% ./build/% ./lint/% ./setup_venv.py ./snippets/%,$(call rwildcard,./,*.py))
STAMP := $(PY:.py=.stamp)
STAMP := $(addprefix build/,$(STAMP))

TEX := $(call rwildcard,./,*.tex)
BIB := $(wildcard *.bib)
IMGS := $(wildcard imgs/*)
SNIPPETS := $(wildcard snippets/*)

CSV := $(filter-out ./bookutil/% ./build/% ./lint/% ./snippets/%,$(call rwildcard,./,*.csv))
CSV := $(addprefix build/,$(CSV))

.PHONY: all
all: $(NAME).pdf

.PHONY: ebook
ebook: $(NAME)-ebook.pdf

.PHONY: printer
printer: $(NAME)-printer.pdf

.PHONY: prepress
prepress: $(NAME)-prepress.pdf

$(NAME).pdf: $(TEX) $(STAMP) $(BIB) $(IMGS) $(SNIPPETS) \
		build/commit-date.tex build/commit-year.tex build/commit-hash.tex
	latexmk -interaction=nonstopmode -xelatex $(NAME)

$(NAME)-ebook.pdf: $(NAME).pdf
	# https://ghostscript.readthedocs.io/en/latest/VectorDevices.html#distiller-parameters
	gs -sDEVICE=pdfwrite \
		-dPDFSETTINGS=/ebook \
		-dPrinted=false \
		-q \
		-o $(NAME)-ebook.pdf \
		$(NAME).pdf

$(NAME)-printer.pdf: $(NAME).pdf
	# https://ghostscript.readthedocs.io/en/latest/VectorDevices.html#distiller-parameters
	gs -sDEVICE=pdfwrite \
		-dPDFSETTINGS=/printer \
		-dPrinted=true \
		-q \
		-o $(NAME)-printer.pdf \
		$(NAME).pdf

$(NAME)-prepress.pdf: $(NAME).pdf
	# https://ghostscript.readthedocs.io/en/latest/VectorDevices.html#distiller-parameters
	gs -sDEVICE=pdfwrite \
		-dPDFSETTINGS=/prepress \
		-dPrinted=true \
		-q \
		-o $(NAME)-prepress.pdf \
		$(NAME).pdf

build/commit-date.tex: .git/refs/heads/$(shell git rev-parse --abbrev-ref HEAD) .git/HEAD
	@mkdir -p $(@D)
	git log -1 --pretty=format:%ad --date="format:%B %-d, %Y" > build/commit-date.tex

build/commit-year.tex: .git/refs/heads/$(shell git rev-parse --abbrev-ref HEAD) .git/HEAD
	@mkdir -p $(@D)
	git log -1 --pretty=format:%ad --date=format:%Y > build/commit-year.tex

build/commit-hash.tex: .git/refs/heads/$(shell git rev-parse --abbrev-ref HEAD) .git/HEAD
	@mkdir -p $(@D)
	echo "\href{https://github.com/calcmogul/$(NAME)/commit/`git rev-parse --short HEAD`}{commit `git rev-parse --short HEAD`}" > build/commit-hash.tex

# This rule places CSVs into the build folder so scripts executed from the build
# folder can use them.
$(CSV): build/%.csv: %.csv
	@mkdir -p $(@D)
	cp $< $@

build/venv.stamp:
	@mkdir -p $(@D)
	python3 setup_venv.py
	./build/venv/bin/pip3 install -e ./bookutil
	./build/venv/bin/pip3 install frccontrol==2022.19 pylint requests
	@touch $@

$(STAMP): build/%.stamp: %.py $(CSV) build/venv.stamp
	@mkdir -p $(@D)
	cd $(@D) && $(abspath ./build/venv/bin/python3) $(abspath ./$<) --noninteractive
	@touch $@

# Run formatters
.PHONY: format
format: build/venv.stamp
	./lint/format_bibliography.py
	./lint/format_eol.py
	./lint/format_paragraph_breaks.py
	cd snippets && clang-format -i *.cpp
	python3 -m black -q .
	git --no-pager diff --exit-code HEAD  # Ensure formatters made no changes

# Run formatters and all linters except link checker. The commit metadata files
# and files generated by Python scripts are dependencies because
# check_tex_includes.py will fail if they're missing.
.PHONY: lint_no_linkcheck
lint_no_linkcheck: format build/commit-date.tex build/commit-year.tex build/commit-hash.tex $(STAMP)
	find . -type f -name \*\.py -print0 | xargs -0 $(abspath ./build/venv/bin/python3) -m pylint
	./lint/check_filenames.py
	./lint/check_tex_includes.py
	./lint/check_tex_labels.py

# Run formatters and linters
.PHONY: lint
lint: lint_no_linkcheck
	./lint/check_links.py

.PHONY: clean
clean: clean_tex
	rm -rf build

.PHONY: clean_tex
clean_tex:
	latexmk -xelatex -C
	rm -f controls-engineering-in-frc-*.pdf

.PHONY: upload_ebook
upload_ebook: ebook
	rsync --progress $(NAME)-ebook.pdf file.tavsys.net:/srv/file/control/$(NAME).pdf

.PHONY: upload_printer
upload_printer: printer
	rsync --progress $(NAME)-printer.pdf file.tavsys.net:/srv/file/control/$(NAME)-printer.pdf

.PHONY: upload_prepress
upload_prepress: prepress
	rsync --progress $(NAME)-prepress.pdf file.tavsys.net:/srv/file/control/$(NAME)-prepress.pdf

.PHONY: upload
upload: upload_ebook upload_printer upload_prepress

.PHONY: setup_archlinux
setup_archlinux:
	sudo pacman -Sy --needed --noconfirm \
		base-devel \
		biber \
		clang \
		ghostscript \
		inkscape \
		perl-clone \
		python \
		python-black \
		python-pip \
		python-pylint \
		python-requests \
		python-wheel \
		texlive-bibtexextra \
		texlive-core \
		texlive-latexextra

.PHONY: setup_ubuntu
setup_ubuntu:
	sudo apt-get update -y
	sudo apt-get install -y \
		biber \
		build-essential \
		cm-super \
		clang-format \
		ghostscript \
		inkscape \
		latexmk \
		python3 \
		python3-pip \
		python3-requests \
		python3-setuptools \
		python3-wheel \
		texlive-bibtex-extra \
		texlive-latex-extra \
		texlive-xetex
	# The Ubuntu 22.04 packages are too old
	pip3 install --user black pylint

.PHONY: setup_macos
setup_macos:
	brew install \
		basictex \
		clang-format \
		ghostscript \
		inkscape
	sudo /Library/TeX/texbin/tlmgr update --self
	sudo /Library/TeX/texbin/tlmgr install \
		biber \
		biblatex \
		cm-super \
		csquotes \
		datatool \
		enumitem \
		footmisc \
		glossaries \
		glossaries-english \
		imakeidx \
		latexmk \
		mdframed \
		mfirstuc \
		needspace \
		placeins \
		titlesec \
		tracklang \
		type1cm \
		was \
		xfor \
		zref
	pip3 install --user black pylint requests wheel
